/** The crawler directory used by robots.txt, bots.txt and crawlers.txt. */

export const BOT_CATEGORIES = [
  {
    category: "Search engines",
    bots: [
      ["Googlebot", "Google Search primary crawler"],
      ["Googlebot-Image", "Google Images"],
      ["Googlebot-News", "Google News"],
      ["Googlebot-Video", "Google Video"],
      ["Googlebot-Mobile", "Google mobile-first indexing"],
      ["Storebot-Google", "Google Shopping product discovery"],
      ["Google-InspectionTool", "Search Console URL inspection"],
      ["GoogleOther", "Google research and product crawling"],
      ["AdsBot-Google", "Google Ads landing page quality"],
      ["AdsBot-Google-Mobile", "Google Ads mobile landing page quality"],
      ["Mediapartners-Google", "Google AdSense"],
      ["APIs-Google", "Google APIs push delivery"],
      ["Bingbot", "Microsoft Bing"],
      ["BingPreview", "Bing page snapshots"],
      ["msnbot", "Legacy Microsoft crawler"],
      ["msnbot-media", "Microsoft media crawler"],
      ["AdIdxBot", "Bing Ads"],
      ["Slurp", "Yahoo Search"],
      ["DuckDuckBot", "DuckDuckGo"],
      ["DuckAssistBot", "DuckDuckGo AI answers"],
      ["Baiduspider", "Baidu Search"],
      ["Baiduspider-image", "Baidu Images"],
      ["YandexBot", "Yandex Search"],
      ["YandexImages", "Yandex Images"],
      ["Sogou web spider", "Sogou Search"],
      ["Exabot", "Exalead"],
      ["SeznamBot", "Seznam Search"],
      ["Qwantify", "Qwant Search"],
      ["NaverBot", "Naver Search"],
      ["Yeti", "Naver primary crawler"],
      ["MojeekBot", "Mojeek independent index"],
      ["Gigabot", "Gigablast"],
    ].map(([name, purpose]) => ({ name, purpose })),
  },
  {
    category: "AI and LLM crawlers",
    bots: [
      ["GPTBot", "OpenAI model training"],
      ["ChatGPT-User", "ChatGPT browsing on behalf of a user"],
      ["OAI-SearchBot", "OpenAI search index"],
      ["anthropic-ai", "Anthropic model training"],
      ["Claude-Web", "Claude browsing"],
      ["ClaudeBot", "Anthropic crawler"],
      ["Claude-User", "Claude acting for a user"],
      ["Claude-SearchBot", "Claude search index"],
      ["Google-Extended", "Google Gemini and Vertex AI training"],
      ["Google-CloudVertexBot", "Google Vertex AI grounding"],
      ["CCBot", "Common Crawl — the base corpus for many models"],
      ["PerplexityBot", "Perplexity AI index"],
      ["Perplexity-User", "Perplexity acting for a user"],
      ["Applebot", "Apple Search and Siri"],
      ["Applebot-Extended", "Apple Intelligence training"],
      ["Amazonbot", "Amazon Alexa and search"],
      ["Bytespider", "ByteDance AI training"],
      ["Meta-ExternalAgent", "Meta AI training"],
      ["Meta-ExternalFetcher", "Meta AI on-demand fetch"],
      ["FacebookBot", "Meta language model training"],
      ["cohere-ai", "Cohere model training"],
      ["cohere-training-data-crawler", "Cohere training corpus"],
      ["Diffbot", "Diffbot knowledge graph"],
      ["omgili", "Webhose / Omgili data collection"],
      ["omgilibot", "Webhose crawler"],
      ["YouBot", "You.com AI search"],
      ["PetalBot", "Huawei Petal Search"],
      ["ImagesiftBot", "ImageSift visual index"],
      ["AI2Bot", "Allen Institute for AI"],
      ["Ai2Bot-Dolma", "AI2 Dolma corpus"],
      ["Kangaroo Bot", "Kangaroo AI index"],
      ["Timpibot", "Timpi decentralised index"],
      ["MistralAI-User", "Mistral AI acting for a user"],
      ["DeepSeekBot", "DeepSeek model training"],
      ["xAI-Bot", "xAI / Grok crawler"],
      ["Devin", "Cognition AI agent"],
      ["QuillBot", "QuillBot AI writing tools"],
    ].map(([name, purpose]) => ({ name, purpose })),
  },
  {
    category: "Social and messaging",
    bots: [
      ["facebookexternalhit", "Facebook link previews"],
      ["Facebot", "Facebook crawler"],
      ["Twitterbot", "X / Twitter cards"],
      ["LinkedInBot", "LinkedIn previews"],
      ["Pinterest", "Pinterest rich pins"],
      ["Pinterestbot", "Pinterest crawler"],
      ["Slackbot", "Slack unfurling"],
      ["Slackbot-LinkExpanding", "Slack link expansion"],
      ["Discordbot", "Discord embeds"],
      ["TelegramBot", "Telegram previews"],
      ["WhatsApp", "WhatsApp link previews"],
      ["redditbot", "Reddit previews"],
      ["SkypeUriPreview", "Skype previews"],
      ["Iframely", "Embed service"],
      ["Embedly", "Embed service"],
      ["nuzzel", "Nuzzel news"],
      ["Snapchat", "Snapchat previews"],
      ["TikTokSpider", "TikTok crawler"],
    ].map(([name, purpose]) => ({ name, purpose })),
  },
  {
    category: "SEO and marketing tools",
    bots: [
      ["AhrefsBot", "Ahrefs backlink index"],
      ["AhrefsSiteAudit", "Ahrefs technical audit"],
      ["SemrushBot", "Semrush index"],
      ["SemrushBot-SA", "Semrush site audit"],
      ["MJ12bot", "Majestic index"],
      ["DotBot", "Moz Link Explorer"],
      ["rogerbot", "Moz Pro campaign crawler"],
      ["Screaming Frog SEO Spider", "Technical SEO audits"],
      ["SiteAuditBot", "Site audit tooling"],
      ["Barkrowler", "Babbar link index"],
      ["DataForSeoBot", "DataForSEO index"],
      ["SEOkicks", "SEOkicks backlink index"],
      ["Seekport Crawler", "Seekport index"],
      ["serpstatbot", "Serpstat index"],
      ["ZoominfoBot", "ZoomInfo business data"],
      ["Sitebulb", "Sitebulb technical audits"],
      ["Lighthouse", "Google Lighthouse performance audits"],
      ["Chrome-Lighthouse", "Core Web Vitals auditing"],
      ["PageSpeed", "PageSpeed Insights"],
      ["GTmetrix", "GTmetrix performance testing"],
      ["WebPageTest", "WebPageTest performance testing"],
    ].map(([name, purpose]) => ({ name, purpose })),
  },
  {
    category: "Commerce, local and review platforms",
    bots: [
      ["Storebot-Google", "Google Shopping"],
      ["PriceGrabber", "Price comparison"],
      ["ShopWiki", "Shopping index"],
      ["BizRate", "Shopping comparison"],
      ["Nextag", "Shopping comparison"],
      ["Shopping.com", "Shopping comparison"],
      ["YelpBot", "Yelp business listings"],
      ["TrustpilotBot", "Trustpilot reviews"],
      ["YellowPagesBot", "Yellow Pages directory"],
      ["FoursquareBot", "Foursquare places"],
      ["TripAdvisor", "TripAdvisor listings"],
      ["CarGurus", "Vehicle marketplace"],
      ["AutoTraderBot", "Vehicle marketplace"],
    ].map(([name, purpose]) => ({ name, purpose })),
  },
  {
    category: "News, archives and academia",
    bots: [
      ["ia_archiver", "Internet Archive"],
      ["archive.org_bot", "Wayback Machine"],
      ["Wayback Save Page", "Wayback on-demand capture"],
      ["heritrix", "Internet Archive Heritrix"],
      ["CommonCrawl", "Common Crawl corpus"],
      ["NewsNow", "News aggregation"],
      ["Feedly", "Feedly RSS reader"],
      ["Inoreader", "Inoreader RSS reader"],
      ["NewsBlur", "NewsBlur RSS reader"],
      ["Bloglovin", "Blog aggregation"],
      ["SuperFeedr", "Feed relay"],
      ["Nutch", "Apache Nutch research crawler"],
      ["ResearchCrawler", "Academic research crawling"],
      ["CiteSeerXBot", "CiteSeerX academic index"],
      ["Scrapy", "Open source research crawler"],
    ].map(([name, purpose]) => ({ name, purpose })),
  },
  {
    category: "Accessibility, monitoring and assistants",
    bots: [
      ["Alexa", "Amazon Alexa voice answers"],
      ["Google-Assistant", "Google Assistant voice answers"],
      ["Siri", "Apple Siri voice answers"],
      ["Cortana", "Microsoft Cortana"],
      ["AccessibilityBot", "Accessibility auditing"],
      ["axe-crawler", "Deque axe accessibility scanning"],
      ["WAVE", "WebAIM WAVE accessibility scanning"],
      ["UptimeRobot", "Uptime monitoring"],
      ["Pingdom", "Uptime and performance monitoring"],
      ["StatusCake", "Uptime monitoring"],
      ["Site24x7", "Uptime monitoring"],
      ["W3C_Validator", "W3C markup validation"],
      ["W3C-checklink", "W3C link checking"],
      ["Google-Structured-Data-Testing-Tool", "Rich results validation"],
      ["Google-Read-Aloud", "Google read-aloud accessibility"],
      ["Google-Site-Verification", "Search Console verification"],
    ].map(([name, purpose]) => ({ name, purpose })),
  },
];

export const ALL_BOTS = BOT_CATEGORIES.flatMap((group) => group.bots);
